//! Berkeley TestFloat conformance test against the **MSL kernels**.
//!
//! Opt-in via `--features testfloat-gpu`. macOS-only (Metal). The
//! `build.rs` compiles vendored Berkeley SoftFloat-3e + TestFloat-3e
//! case generators (`vendor/`) into a static library that this test
//! links to. Inputs are generated by TestFloat's case generator,
//! expected outputs by SoftFloat-3e — both linked C, no testfloat_gen
//! pipe — and dispatched in batches through the existing
//! `gpu::*_batch` MSL kernels.
//!
//! Compared with the CPU `testfloat` harness this reaches GPU-bound
//! throughput: vectors flow at memory bandwidth instead of pipe rate.
//!
//! NaN payload differences are tolerated: SoftFloat's canonical qNaN
//! is `0xFFF8_0000_0000_0000`; this crate's MSL canonicalizes to
//! `0x7FF8_0000_0000_0000`. Both classify as NaN and the comparator
//! treats any-NaN as equal. Status flags are not exposed and not
//! compared.
//!
//! `ftz` and `testfloat-gpu` are mutually exclusive: TestFloat's
//! vectors assume IEEE-754 §7.4 gradual underflow, FTZ violates it.

#![cfg(all(feature = "testfloat-gpu", target_os = "macos", not(feature = "ftz")))]
#![allow(clippy::missing_safety_doc)]

use std::sync::Mutex;

use metal_softfloat_core::{gpu, RoundingMode};

// ---- SoftFloat-3e FFI ------------------------------------------------------

/// Bit-pattern wrapper matching SoftFloat's `typedef struct { uint64_t v; } float64_t;`
#[repr(C)]
#[derive(Clone, Copy)]
struct F64 {
    v: u64,
}

/// Matches SoftFloat's `typedef struct { uint32_t v; } float32_t;`
#[repr(C)]
#[derive(Clone, Copy)]
struct F32 {
    v: u32,
}

// SoftFloat rounding-mode codes (softfloat.h `softfloat_round_*`).
const SF_ROUND_NEAR_EVEN: u8 = 0;
const SF_ROUND_MINMAG: u8 = 1;
const SF_ROUND_MIN: u8 = 2;
const SF_ROUND_MAX: u8 = 3;

fn sf_mode(m: RoundingMode) -> u8 {
    match m {
        RoundingMode::Nearest => SF_ROUND_NEAR_EVEN,
        RoundingMode::Down => SF_ROUND_MIN,
        RoundingMode::Up => SF_ROUND_MAX,
        RoundingMode::Zero => SF_ROUND_MINMAG,
    }
}

extern "C" {
    static mut softfloat_roundingMode: u8;

    fn f64_add(a: F64, b: F64) -> F64;
    fn f64_sub(a: F64, b: F64) -> F64;
    fn f64_mul(a: F64, b: F64) -> F64;
    fn f64_div(a: F64, b: F64) -> F64;
    fn f64_sqrt(a: F64) -> F64;
    #[allow(non_snake_case)]
    fn f64_mulAdd(a: F64, b: F64, c: F64) -> F64;

    fn i64_to_f64(a: i64) -> F64;
    fn ui64_to_f64(a: u64) -> F64;
    fn f64_to_i64(a: F64, roundingMode: u8, exact: bool) -> i64;
    fn f32_to_f64(a: F32) -> F64;
    fn f64_to_f32(a: F64) -> F32;

    fn f64_eq(a: F64, b: F64) -> bool;
    fn f64_lt_quiet(a: F64, b: F64) -> bool;
    fn f64_le_quiet(a: F64, b: F64) -> bool;
}

// ---- TestFloat-3e case generator FFI ---------------------------------------

extern "C" {
    fn genCases_setLevel(level: std::os::raw::c_int);
    static mut genCases_done: bool;
    static mut genCases_f64_a: F64;
    static mut genCases_f64_b: F64;
    static mut genCases_f64_c: F64;
    static mut genCases_f32_a: F32;
    static mut genCases_i64_a: i64;
    static mut genCases_ui64_a: u64;

    fn genCases_f64_a_init();
    fn genCases_f64_a_next();
    fn genCases_f64_ab_init();
    fn genCases_f64_ab_next();
    fn genCases_f64_abc_init();
    fn genCases_f64_abc_next();
    fn genCases_f32_a_init();
    fn genCases_f32_a_next();
    fn genCases_i64_a_init();
    fn genCases_i64_a_next();
    fn genCases_ui64_a_init();
    fn genCases_ui64_a_next();
}

// ---- Helpers ---------------------------------------------------------------

/// Process-wide lock around the C state (SoftFloat + TestFloat globals).
/// `cargo test` runs `#[test]` functions in parallel by default; this
/// serializes them so the case-gen state machine and `softfloat_roundingMode`
/// don't get clobbered. The MSL queue is a single shared resource anyway,
/// so per-test concurrency wouldn't help.
static C_STATE: Mutex<()> = Mutex::new(());

fn level() -> i32 {
    std::env::var("TESTFLOAT_LEVEL")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(1)
}

/// fma at TestFloat level 2 is `2 * f64NumQInP2³` ≈ 181 billion vectors per
/// rounding mode (×4 modes ≈ 723 B). Even pure case-generator iteration —
/// before computing any expected output — would take many hours. We cap fma
/// at level 1 by default so a `TESTFLOAT_LEVEL=2` run remains tractable;
/// override with `TESTFLOAT_FMA_LEVEL=2` if you have time to burn. The
/// 2-arg ops (`* f64NumQInP2²`) and sqrt run at the requested level
/// unchanged.
fn fma_level() -> i32 {
    if let Some(l) = std::env::var("TESTFLOAT_FMA_LEVEL")
        .ok()
        .and_then(|s| s.parse().ok())
    {
        return l;
    }
    1
}

fn is_nan(bits: u64) -> bool {
    let exp = (bits >> 52) & 0x7FF;
    let mant = bits & ((1u64 << 52) - 1);
    exp == 0x7FF && mant != 0
}

fn is_nan_f32(bits: u32) -> bool {
    let exp = (bits >> 23) & 0xFF;
    let mant = bits & 0x7F_FFFF;
    exp == 0xFF && mant != 0
}

fn results_match(got: u64, expected: u64) -> bool {
    got == expected || (is_nan(got) && is_nan(expected))
}

fn results_match_f32(got: u32, expected: u32) -> bool {
    got == expected || (is_nan_f32(got) && is_nan_f32(expected))
}

/// f64 → i64 has implementation-defined behavior for NaN, ±Inf, and
/// out-of-range finite values (IEEE-754 §5.4.1). Berkeley SoftFloat's
/// 8086-SSE specialization returns `i64::MIN` for every such case; this
/// crate returns `0` (NaN), `i64::MIN` (neg overflow / -Inf), or `i64::MAX`
/// (pos overflow / +Inf). Treat both as agreeing whenever Berkeley
/// signaled out-of-range and we returned any of the three saturating
/// defaults. In-range integer values must still match exactly.
fn cvt_f64_to_i64_match(got: i64, expected: i64) -> bool {
    if got == expected {
        return true;
    }
    expected == i64::MIN && (got == i64::MAX || got == 0)
}

/// Larger batches amortize MTLCommandBuffer launch overhead better but
/// cost RAM (24-byte op2 input × N + 8-byte output × N). 64K is a
/// reasonable middle: ~2 MB working set, ~30 µs launch ~ negligible
/// against the GPU compute time.
const BATCH: usize = 65_536;
const MAX_REPORTED: usize = 16;

struct Reporter {
    op: &'static str,
    mode: RoundingMode,
    total: u64,
    mismatches: Vec<String>,
}

impl Reporter {
    fn new(op: &'static str, mode: RoundingMode) -> Self {
        Self { op, mode, total: 0, mismatches: Vec::new() }
    }

    fn ingest(&mut self, args: &dyn std::fmt::Display, expected: u64, got: u64) {
        self.total += 1;
        if !results_match(got, expected) && self.mismatches.len() < MAX_REPORTED {
            self.mismatches.push(format!("args=[{args}] expected={expected:016x} got={got:016x}"));
        }
    }

    fn finish(self) {
        assert!(self.total > 0, "no vectors produced for {} {:?}", self.op, self.mode);
        assert!(
            self.mismatches.is_empty(),
            "{} mismatches against TestFloat (op={}, mode={:?}, vectors={}). first {}:\n  {}",
            self.mismatches.len(),
            self.op,
            self.mode,
            self.total,
            self.mismatches.len(),
            self.mismatches.join("\n  ")
        );
        eprintln!("[testfloat-gpu] {} {:?}: {} vectors OK", self.op, self.mode, self.total);
    }
}

// ---- Per-arity drivers -----------------------------------------------------

fn run_op1(
    op: &'static str,
    mode: RoundingMode,
    lvl: i32,
    sf: unsafe extern "C" fn(F64) -> F64,
    gpu_batch: fn(&[(u64, RoundingMode)]) -> Vec<u64>,
) {
    let _guard = C_STATE.lock().unwrap();
    let mut rep = Reporter::new(op, mode);
    let mut batch: Vec<(u64, RoundingMode)> = Vec::with_capacity(BATCH);
    let mut expected: Vec<u64> = Vec::with_capacity(BATCH);

    unsafe {
        softfloat_roundingMode = sf_mode(mode);
        genCases_setLevel(lvl);
        genCases_f64_a_init();

        loop {
            genCases_f64_a_next();
            let done = genCases_done;
            let a = genCases_f64_a.v;
            let exp = sf(F64 { v: a }).v;
            batch.push((a, mode));
            expected.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu_batch(&batch);
                for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
                    let (a_in, _) = batch[i];
                    rep.ingest(&format_args!("{a_in:016x}"), *e, *g);
                }
                batch.clear();
                expected.clear();
            }
            if done {
                break;
            }
        }
    }
    rep.finish();
}

fn run_op2(
    op: &'static str,
    mode: RoundingMode,
    lvl: i32,
    sf: unsafe extern "C" fn(F64, F64) -> F64,
    gpu_batch: fn(&[(u64, u64, RoundingMode)]) -> Vec<u64>,
) {
    let _guard = C_STATE.lock().unwrap();
    let mut rep = Reporter::new(op, mode);
    let mut batch: Vec<(u64, u64, RoundingMode)> = Vec::with_capacity(BATCH);
    let mut expected: Vec<u64> = Vec::with_capacity(BATCH);

    unsafe {
        softfloat_roundingMode = sf_mode(mode);
        genCases_setLevel(lvl);
        genCases_f64_ab_init();

        loop {
            genCases_f64_ab_next();
            let done = genCases_done;
            let a = genCases_f64_a.v;
            let b = genCases_f64_b.v;
            let exp = sf(F64 { v: a }, F64 { v: b }).v;
            batch.push((a, b, mode));
            expected.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu_batch(&batch);
                for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
                    let (a_in, b_in, _) = batch[i];
                    rep.ingest(&format_args!("{a_in:016x}, {b_in:016x}"), *e, *g);
                }
                batch.clear();
                expected.clear();
            }
            if done {
                break;
            }
        }
    }
    rep.finish();
}

fn run_op3(
    op: &'static str,
    mode: RoundingMode,
    lvl: i32,
    sf: unsafe extern "C" fn(F64, F64, F64) -> F64,
    gpu_batch: fn(&[(u64, u64, u64, RoundingMode)]) -> Vec<u64>,
) {
    let _guard = C_STATE.lock().unwrap();
    let mut rep = Reporter::new(op, mode);
    let mut batch: Vec<(u64, u64, u64, RoundingMode)> = Vec::with_capacity(BATCH);
    let mut expected: Vec<u64> = Vec::with_capacity(BATCH);

    unsafe {
        softfloat_roundingMode = sf_mode(mode);
        genCases_setLevel(lvl);
        genCases_f64_abc_init();

        loop {
            genCases_f64_abc_next();
            let done = genCases_done;
            let a = genCases_f64_a.v;
            let b = genCases_f64_b.v;
            let c = genCases_f64_c.v;
            let exp = sf(F64 { v: a }, F64 { v: b }, F64 { v: c }).v;
            batch.push((a, b, c, mode));
            expected.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu_batch(&batch);
                for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
                    let (a_in, b_in, c_in, _) = batch[i];
                    rep.ingest(&format_args!("{a_in:016x}, {b_in:016x}, {c_in:016x}"), *e, *g);
                }
                batch.clear();
                expected.clear();
            }
            if done {
                break;
            }
        }
    }
    rep.finish();
}

// ---- Conversion + comparison runners ---------------------------------------

fn run_cvt_i64_to_f64(op: &'static str, mode: RoundingMode, lvl: i32) {
    let _guard = C_STATE.lock().unwrap();
    let mut rep = Reporter::new(op, mode);
    let mut batch: Vec<(i64, RoundingMode)> = Vec::with_capacity(BATCH);
    let mut expected: Vec<u64> = Vec::with_capacity(BATCH);
    unsafe {
        softfloat_roundingMode = sf_mode(mode);
        genCases_setLevel(lvl);
        genCases_i64_a_init();
        loop {
            genCases_i64_a_next();
            let done = genCases_done;
            let a = genCases_i64_a;
            let exp = i64_to_f64(a).v;
            batch.push((a, mode));
            expected.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu::cvt_i64_to_f64_batch(&batch);
                for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
                    rep.ingest(&format_args!("{:016x}", batch[i].0 as u64), *e, *g);
                }
                batch.clear();
                expected.clear();
            }
            if done { break; }
        }
    }
    rep.finish();
}

fn run_cvt_u64_to_f64(op: &'static str, mode: RoundingMode, lvl: i32) {
    let _guard = C_STATE.lock().unwrap();
    let mut rep = Reporter::new(op, mode);
    let mut batch: Vec<(u64, RoundingMode)> = Vec::with_capacity(BATCH);
    let mut expected: Vec<u64> = Vec::with_capacity(BATCH);
    unsafe {
        softfloat_roundingMode = sf_mode(mode);
        genCases_setLevel(lvl);
        genCases_ui64_a_init();
        loop {
            genCases_ui64_a_next();
            let done = genCases_done;
            let a = genCases_ui64_a;
            let exp = ui64_to_f64(a).v;
            batch.push((a, mode));
            expected.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu::cvt_u64_to_f64_batch(&batch);
                for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
                    rep.ingest(&format_args!("{:016x}", batch[i].0), *e, *g);
                }
                batch.clear();
                expected.clear();
            }
            if done { break; }
        }
    }
    rep.finish();
}

fn run_cvt_f64_to_i64(op: &'static str, mode: RoundingMode, lvl: i32) {
    let _guard = C_STATE.lock().unwrap();
    let mut rep = Reporter::new(op, mode);
    let mut batch: Vec<(u64, RoundingMode)> = Vec::with_capacity(BATCH);
    let mut expected_v: Vec<i64> = Vec::with_capacity(BATCH);
    let sfm = sf_mode(mode);
    unsafe {
        softfloat_roundingMode = sfm;
        genCases_setLevel(lvl);
        genCases_f64_a_init();
        loop {
            genCases_f64_a_next();
            let done = genCases_done;
            let a = genCases_f64_a.v;
            let exp = f64_to_i64(F64 { v: a }, sfm, false);
            batch.push((a, mode));
            expected_v.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu::cvt_f64_to_i64_batch(&batch);
                rep.total += got.len() as u64;
                for (i, (g, e)) in got.iter().zip(expected_v.iter()).enumerate() {
                    if !cvt_f64_to_i64_match(*g, *e) && rep.mismatches.len() < MAX_REPORTED {
                        let a_in = batch[i].0;
                        rep.mismatches.push(format!(
                            "args=[{a_in:016x}] expected={e} got={g}"
                        ));
                    }
                }
                batch.clear();
                expected_v.clear();
            }
            if done { break; }
        }
    }
    // rep.finish counts via rep.total which we incremented above; just check
    // the assertions.
    assert!(rep.total > 0, "no vectors produced for {} {:?}", rep.op, rep.mode);
    assert!(
        rep.mismatches.is_empty(),
        "{} mismatches against TestFloat (op={}, mode={:?}, vectors={}). first {}:\n  {}",
        rep.mismatches.len(), rep.op, rep.mode, rep.total,
        rep.mismatches.len(), rep.mismatches.join("\n  ")
    );
    eprintln!("[testfloat-gpu] {} {:?}: {} vectors OK", rep.op, rep.mode, rep.total);
}

fn run_cvt_f32_to_f64(lvl: i32) {
    let _guard = C_STATE.lock().unwrap();
    // f32 → f64 is exact, no rounding mode involved. We still pass Nearest
    // through Reporter for the mode label.
    let mut rep = Reporter::new("f32_to_f64", RoundingMode::Nearest);
    let mut batch: Vec<u32> = Vec::with_capacity(BATCH);
    let mut expected: Vec<u64> = Vec::with_capacity(BATCH);
    unsafe {
        genCases_setLevel(lvl);
        genCases_f32_a_init();
        loop {
            genCases_f32_a_next();
            let done = genCases_done;
            let a = genCases_f32_a.v;
            let exp = f32_to_f64(F32 { v: a }).v;
            batch.push(a);
            expected.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu::cvt_f32_to_f64_batch(&batch);
                for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
                    rep.ingest(&format_args!("{:08x}", batch[i]), *e, *g);
                }
                batch.clear();
                expected.clear();
            }
            if done { break; }
        }
    }
    rep.finish();
}

fn run_cvt_f64_to_f32(op: &'static str, mode: RoundingMode, lvl: i32) {
    let _guard = C_STATE.lock().unwrap();
    let mut rep = Reporter::new(op, mode);
    let mut batch: Vec<(u64, RoundingMode)> = Vec::with_capacity(BATCH);
    let mut expected_v: Vec<u32> = Vec::with_capacity(BATCH);
    unsafe {
        softfloat_roundingMode = sf_mode(mode);
        genCases_setLevel(lvl);
        genCases_f64_a_init();
        loop {
            genCases_f64_a_next();
            let done = genCases_done;
            let a = genCases_f64_a.v;
            let exp = f64_to_f32(F64 { v: a }).v;
            batch.push((a, mode));
            expected_v.push(exp);
            if batch.len() >= BATCH || done {
                let got = gpu::cvt_f64_to_f32_batch(&batch);
                rep.total += got.len() as u64;
                for (i, (g, e)) in got.iter().zip(expected_v.iter()).enumerate() {
                    if !results_match_f32(*g, *e) && rep.mismatches.len() < MAX_REPORTED {
                        let a_in = batch[i].0;
                        rep.mismatches.push(format!(
                            "args=[{a_in:016x}] expected={e:08x} got={g:08x}"
                        ));
                    }
                }
                batch.clear();
                expected_v.clear();
            }
            if done { break; }
        }
    }
    assert!(rep.total > 0, "no vectors produced for {} {:?}", rep.op, rep.mode);
    assert!(
        rep.mismatches.is_empty(),
        "{} mismatches against TestFloat (op={}, mode={:?}, vectors={}). first {}:\n  {}",
        rep.mismatches.len(), rep.op, rep.mode, rep.total,
        rep.mismatches.len(), rep.mismatches.join("\n  ")
    );
    eprintln!("[testfloat-gpu] {} {:?}: {} vectors OK", rep.op, rep.mode, rep.total);
}

/// Comparison kind for the unified compare runner.
#[derive(Clone, Copy)]
enum Cmp {
    Eq,
    Lt,
    Le,
    Gt,
    Ge,
}

fn run_cmp(op: &'static str, kind: Cmp, lvl: i32) {
    let _guard = C_STATE.lock().unwrap();
    // No rounding mode; use Nearest as the label for Reporter.
    let mut rep = Reporter::new(op, RoundingMode::Nearest);
    let mut batch: Vec<(u64, u64)> = Vec::with_capacity(BATCH);
    let mut expected: Vec<bool> = Vec::with_capacity(BATCH);
    unsafe {
        genCases_setLevel(lvl);
        genCases_f64_ab_init();
        loop {
            genCases_f64_ab_next();
            let done = genCases_done;
            let a = genCases_f64_a.v;
            let b = genCases_f64_b.v;
            // Map fgt(a,b) → lt_quiet(b,a); fge(a,b) → le_quiet(b,a).
            let exp = match kind {
                Cmp::Eq => f64_eq(F64 { v: a }, F64 { v: b }),
                Cmp::Lt => f64_lt_quiet(F64 { v: a }, F64 { v: b }),
                Cmp::Le => f64_le_quiet(F64 { v: a }, F64 { v: b }),
                Cmp::Gt => f64_lt_quiet(F64 { v: b }, F64 { v: a }),
                Cmp::Ge => f64_le_quiet(F64 { v: b }, F64 { v: a }),
            };
            batch.push((a, b));
            expected.push(exp);
            if batch.len() >= BATCH || done {
                let got: Vec<bool> = match kind {
                    Cmp::Eq => gpu::feq_batch(&batch),
                    Cmp::Lt => gpu::flt_batch(&batch),
                    Cmp::Le => gpu::fle_batch(&batch),
                    Cmp::Gt => gpu::fgt_batch(&batch),
                    Cmp::Ge => gpu::fge_batch(&batch),
                };
                rep.total += got.len() as u64;
                for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
                    if g != e && rep.mismatches.len() < MAX_REPORTED {
                        let (a_in, b_in) = batch[i];
                        rep.mismatches.push(format!(
                            "args=[{a_in:016x}, {b_in:016x}] expected={e} got={g}"
                        ));
                    }
                }
                batch.clear();
                expected.clear();
            }
            if done { break; }
        }
    }
    assert!(rep.total > 0, "no vectors produced for {} {:?}", rep.op, rep.mode);
    assert!(
        rep.mismatches.is_empty(),
        "{} mismatches against TestFloat (op={}, vectors={}). first {}:\n  {}",
        rep.mismatches.len(), rep.op, rep.total,
        rep.mismatches.len(), rep.mismatches.join("\n  ")
    );
    eprintln!("[testfloat-gpu] {} {:?}: {} vectors OK", rep.op, rep.mode, rep.total);
}

// ---- Tests -----------------------------------------------------------------

macro_rules! op2_tests {
    ($prefix:ident, $op:literal, $sf:ident, $gpu_batch:ident) => {
        mod $prefix {
            use super::*;
            #[test]
            fn nearest() { run_op2($op, RoundingMode::Nearest, level(), $sf, gpu::$gpu_batch); }
            #[test]
            fn down()    { run_op2($op, RoundingMode::Down,    level(), $sf, gpu::$gpu_batch); }
            #[test]
            fn up()      { run_op2($op, RoundingMode::Up,      level(), $sf, gpu::$gpu_batch); }
            #[test]
            fn zero()    { run_op2($op, RoundingMode::Zero,    level(), $sf, gpu::$gpu_batch); }
        }
    };
}

op2_tests!(f64_add, "f64_add", f64_add, fadd_batch);
op2_tests!(f64_sub, "f64_sub", f64_sub, fsub_batch);
op2_tests!(f64_mul, "f64_mul", f64_mul, fmul_batch);
op2_tests!(f64_div, "f64_div", f64_div, fdiv_batch);

mod f64_sqrt {
    use super::*;
    #[test]
    fn nearest() { run_op1("f64_sqrt", RoundingMode::Nearest, level(), f64_sqrt, gpu::fsqrt_batch); }
    #[test]
    fn down()    { run_op1("f64_sqrt", RoundingMode::Down,    level(), f64_sqrt, gpu::fsqrt_batch); }
    #[test]
    fn up()      { run_op1("f64_sqrt", RoundingMode::Up,      level(), f64_sqrt, gpu::fsqrt_batch); }
    #[test]
    fn zero()    { run_op1("f64_sqrt", RoundingMode::Zero,    level(), f64_sqrt, gpu::fsqrt_batch); }
}

mod f64_muladd {
    use super::*;
    #[test]
    fn nearest() { run_op3("f64_mulAdd", RoundingMode::Nearest, fma_level(), f64_mulAdd, gpu::fma_batch); }
    #[test]
    fn down()    { run_op3("f64_mulAdd", RoundingMode::Down,    fma_level(), f64_mulAdd, gpu::fma_batch); }
    #[test]
    fn up()      { run_op3("f64_mulAdd", RoundingMode::Up,      fma_level(), f64_mulAdd, gpu::fma_batch); }
    #[test]
    fn zero()    { run_op3("f64_mulAdd", RoundingMode::Zero,    fma_level(), f64_mulAdd, gpu::fma_batch); }
}

// ---- Conversion + comparison tests -----------------------------------------

mod cvt_i64_to_f64 {
    use super::*;
    #[test]
    fn nearest() { run_cvt_i64_to_f64("i64_to_f64", RoundingMode::Nearest, level()); }
    #[test]
    fn down()    { run_cvt_i64_to_f64("i64_to_f64", RoundingMode::Down,    level()); }
    #[test]
    fn up()      { run_cvt_i64_to_f64("i64_to_f64", RoundingMode::Up,      level()); }
    #[test]
    fn zero()    { run_cvt_i64_to_f64("i64_to_f64", RoundingMode::Zero,    level()); }
}

mod cvt_u64_to_f64 {
    use super::*;
    #[test]
    fn nearest() { run_cvt_u64_to_f64("ui64_to_f64", RoundingMode::Nearest, level()); }
    #[test]
    fn down()    { run_cvt_u64_to_f64("ui64_to_f64", RoundingMode::Down,    level()); }
    #[test]
    fn up()      { run_cvt_u64_to_f64("ui64_to_f64", RoundingMode::Up,      level()); }
    #[test]
    fn zero()    { run_cvt_u64_to_f64("ui64_to_f64", RoundingMode::Zero,    level()); }
}

mod cvt_f64_to_i64 {
    use super::*;
    #[test]
    fn nearest() { run_cvt_f64_to_i64("f64_to_i64", RoundingMode::Nearest, level()); }
    #[test]
    fn down()    { run_cvt_f64_to_i64("f64_to_i64", RoundingMode::Down,    level()); }
    #[test]
    fn up()      { run_cvt_f64_to_i64("f64_to_i64", RoundingMode::Up,      level()); }
    #[test]
    fn zero()    { run_cvt_f64_to_i64("f64_to_i64", RoundingMode::Zero,    level()); }
}

#[test]
fn cvt_f32_to_f64() { run_cvt_f32_to_f64(level()); }

mod cvt_f64_to_f32 {
    use super::*;
    #[test]
    fn nearest() { run_cvt_f64_to_f32("f64_to_f32", RoundingMode::Nearest, level()); }
    #[test]
    fn down()    { run_cvt_f64_to_f32("f64_to_f32", RoundingMode::Down,    level()); }
    #[test]
    fn up()      { run_cvt_f64_to_f32("f64_to_f32", RoundingMode::Up,      level()); }
    #[test]
    fn zero()    { run_cvt_f64_to_f32("f64_to_f32", RoundingMode::Zero,    level()); }
}

#[test] fn feq() { run_cmp("f64_eq", Cmp::Eq, level()); }
#[test] fn flt() { run_cmp("f64_lt", Cmp::Lt, level()); }
#[test] fn fle() { run_cmp("f64_le", Cmp::Le, level()); }
#[test] fn fgt() { run_cmp("f64_gt", Cmp::Gt, level()); }
#[test] fn fge() { run_cmp("f64_ge", Cmp::Ge, level()); }
